version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/taskmanager.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=15
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-3.5-turbo
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    networks:
      - taskmanager-network

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - VITE_APP_NAME=TaskManager
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000
    networks:
      - taskmanager-network

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: taskmanager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - taskmanager-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: taskmanager-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - taskmanager-network

  # Development Database UI (optional)
  adminer:
    image: adminer:latest
    container_name: taskmanager-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    volumes:
      - ./data:/data
    networks:
      - taskmanager-network
    profiles:
      - dev

  # API Documentation
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: taskmanager-swagger
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON_URL=http://localhost:8000/openapi.json
    networks:
      - taskmanager-network
    profiles:
      - dev

networks:
  taskmanager-network:
    driver: bridge

volumes:
  redis-data:
  data: