integrations:
  github:
    api_version: v4
    endpoints:
      - repos
      - user_profile
      - contributions
    authentication:
      type: oauth2
      scopes:
        - read:user
        - read:repo
    rate_limits:
      max_requests_per_minute: 60
      backoff_strategy: exponential

  openai:
    api_version: 2023-09-01
    models:
      - gpt-4
      - gpt-3.5-turbo
    endpoints:
      - content_generation
      - grammar_check
      - seo_optimization
    authentication:
      type: bearer_token
    rate_limits:
      max_requests_per_minute: 20
      backoff_strategy: linear

  oauth_providers:
    github:
      client_id: ${GITHUB_CLIENT_ID}
      scope: user:email,read:user
      flow: authorization_code

    google:
      client_id: ${GOOGLE_CLIENT_ID}
      scope: profile,email
      flow: authorization_code

  security:
    encryption: AES-256
    token_rotation: true
    max_token_age_days: 30